using System.Collections.Generic;
using System.Xml.Linq;

namespace DotNetProjectParser.ProjectModel
{
    /// <summary>
    /// A model of the Project object
    /// </summary>
    public class Project
    {
        /// <summary>
        /// Project name
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Full path to project
        /// </summary>
        public string FullPath { get; set; }
        
        /// <summary>
        /// Project document as XML - if project file was XML
        /// </summary>
        public XDocument ProjectXml { get; set; }


        /// <summary>
        /// Path of the project folder
        /// </summary>
        public string DirectoryPath { get; set; }
        
        /// <summary>
        /// Name of the assembly generated by project (without extension)
        /// </summary>
        public string AssemblyName { get; set; }

        /// <summary>
        /// The output type 
        /// </summary>
        public string OutputType { get; set; }
        
        /// <summary>
        /// The target framework
        /// </summary>
        public string TargetFramework { get; set; }
        
        /// <summary>
        /// The extension of the generated assembly
        /// </summary>
        public string TargetExtension { get; set; }

        /// <summary>
        /// The items included in the project
        /// </summary>
        public ICollection<ProjectItem> Items { get; } = new List<ProjectItem>();

    }


}